// https://www.rhein-neckar-kreis.de/site/Rhein-Neckar-Kreis-2016/get/documents_E1249267876/rhein-neckar-kreis/Daten/Infomaterial/Bev%C3%B6lkerungsfortschreibung.pdf

export default [
    { city: 'Altlußheim', numberOfHabitants: 6204 },
    { city: 'Angelbachtal', numberOfHabitants: 5110 },
    { city: 'Bammental', numberOfHabitants: 6594 },
    { city: 'Brühl', numberOfHabitants: 14337 },
    { city: 'Dielheim', numberOfHabitants: 9095 },
    { city: 'Dossenheim', numberOfHabitants: 12574 },
    { city: 'Eberbach', numberOfHabitants: 14390 },
    { city: 'Edingen-Neckarhausen', numberOfHabitants: 14171 },
    { city: 'Epfenbach', numberOfHabitants: 2388 },
    { city: 'Eppelheim', numberOfHabitants: 15356 },
    { city: 'Eschelbronn', numberOfHabitants: 2664 },
    { city: 'Gaiberg', numberOfHabitants: 2407 },
    { city: 'Heddesbach', numberOfHabitants: 463 },
    { city: 'Heddesheim', numberOfHabitants: 11745 },
    { city: 'Heiligkreuzsteinach', numberOfHabitants: 2641 },
    { city: 'Helmstadt-Bargen', numberOfHabitants: 3802 },
    { city: 'Hemsbach', numberOfHabitants: 11691 },
    { city: 'Hirschberg', numberOfHabitants: 9883 },
    { city: 'Hockenheim', numberOfHabitants: 21743 },
    { city: 'Ilvesheim', numberOfHabitants: 9339 },
    { city: 'Ketsch', numberOfHabitants: 12887 },
    { city: 'Ladenburg', numberOfHabitants: 11776 },
    { city: 'Laudenbach', numberOfHabitants: 6382 },
    { city: 'Leimen', numberOfHabitants: 26979 },
    { city: 'Lobbach', numberOfHabitants: 2366 },
    { city: 'Malsch', numberOfHabitants: 3445 },
    { city: 'Mauer', numberOfHabitants: 4067 },
    { city: 'Meckesheim', numberOfHabitants: 5166 },
    { city: 'Mühlhausen', numberOfHabitants: 8650 },
    { city: 'Neckarbischofsheim', numberOfHabitants: 4050 },
    { city: 'Neckargemünd', numberOfHabitants: 13388 },
    { city: 'Neidenstein', numberOfHabitants: 1739 },
    { city: 'Neulußheim', numberOfHabitants: 7136 },
    { city: 'Nußloch', numberOfHabitants: 11271 },
    { city: 'Oftersheim', numberOfHabitants: 12234 },
    { city: 'Plankstadt', numberOfHabitants: 10407 },
    { city: 'Rauenberg', numberOfHabitants: 8770 },
    { city: 'Reichartshausen', numberOfHabitants: 2078 },
    { city: 'Reilingen', numberOfHabitants: 7816 },
    { city: 'Sandhausen', numberOfHabitants: 15276 },
    { city: 'Schönau', numberOfHabitants: 4392 },
    { city: 'Schönbrunn', numberOfHabitants: 2880 },
    { city: 'Schriesheim', numberOfHabitants: 14953 },
    { city: 'Schwetzingen', numberOfHabitants: 21592 },
    { city: 'Sinsheim', numberOfHabitants: 35398 },
    { city: 'Spechbach', numberOfHabitants: 1719 },
    { city: 'St. Leon-Rot', numberOfHabitants: 13729 },
    { city: 'Waibstadt', numberOfHabitants: 5616 },
    { city: 'Walldorf', numberOfHabitants: 15446 },
    { city: 'Weinheim', numberOfHabitants: 45317 },
    { city: 'Wiesenbach', numberOfHabitants: 3109 },
    { city: 'Wiesloch', numberOfHabitants: 26706 },
    { city: 'Wilhelmsfeld', numberOfHabitants: 3171 },
    { city: 'Zuzenhausen', numberOfHabitants: 2180 }
];